---
apiVersion: kustomize.toolkit.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: realtimeapp-dev
  namespace: flux-system
spec:
  healthChecks:
    - kind: Deployment
      name: realtime-dev
      namespace: realtime-dev
    - kind: Deployment
      name: redis-dev
      namespace: realtime-dev
  interval: 1m0s
  path: ./deploy/overlay/dev
  prune: true
  sourceRef:
    kind: GitRepository
    name: realtimeapp-infra
  timeout: 20s
  validation: client
